version: '3.8'
services:
  db:
    image: postgres:15
    container_name: paystackdb
    environment:
      POSTGRES_DB: paystackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aju@2024!
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: paystack-app
    depends_on:
      - db
    ports:
      - "8089:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paystackdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aju@2024!
volumes:
  pgdata: 