spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paystackdb
    username: paystackuser
    password: paystackpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thefearlessmovement1@gmail.com
    password: cgzm kcvl dgjr bupt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

qr:
  redirect-base-url: "https://thefearlessmovement.co.ke"